# Generated by Django 6.0.7 on 2026-08-04 02:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AadhaarApplication",
            fields=[
                (
                    "application_id",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "status_level",
                    models.IntegerField(
                        choices=[
                            (1, "Submitted"),
                            (2, "Under Review"),
                            (3, "Approved"),
                            (4, "Completed"),
                            (5, "Rejected"),
                        ],
                        default=1,
                    ),
                ),
                ("applied_by_email", models.EmailField(max_length=254)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("name", models.CharField(max_length=100)),
                ("aadhaar_number", models.CharField(max_length=255)),
                ("dob", models.DateField()),
                (
                    "old_mobile",
                    models.CharField(
                        max_length=10,
                        validators=[django.core.validators.RegexValidator("^\\d{10}$")],
                    ),
                ),
                (
                    "new_mobile",
                    models.CharField(
                        max_length=10,
                        validators=[django.core.validators.RegexValidator("^\\d{10}$")],
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("address", models.TextField()),
                ("document", models.FileField(upload_to="aadhaar_docs/")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="OTPStore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("otp", models.CharField(max_length=6)),
                ("created_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="PanApplication",
            fields=[
                (
                    "application_id",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "status_level",
                    models.IntegerField(
                        choices=[
                            (1, "Submitted"),
                            (2, "Under Review"),
                            (3, "Approved"),
                            (4, "Completed"),
                            (5, "Rejected"),
                        ],
                        default=1,
                    ),
                ),
                ("applied_by_email", models.EmailField(max_length=254)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("name", models.CharField(max_length=100)),
                ("father_name", models.CharField(max_length=100)),
                ("dob", models.DateField()),
                ("gender", models.CharField(max_length=10)),
                (
                    "mobile",
                    models.CharField(
                        max_length=10,
                        validators=[django.core.validators.RegexValidator("^\\d{10}$")],
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("address", models.TextField()),
                ("identity_proof", models.FileField(upload_to="pan_docs/id/")),
                ("address_proof", models.FileField(upload_to="pan_docs/address/")),
                ("photo", models.ImageField(upload_to="pan_docs/photos/")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="VoterApplication",
            fields=[
                (
                    "application_id",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "status_level",
                    models.IntegerField(
                        choices=[
                            (1, "Submitted"),
                            (2, "Under Review"),
                            (3, "Approved"),
                            (4, "Completed"),
                            (5, "Rejected"),
                        ],
                        default=1,
                    ),
                ),
                ("applied_by_email", models.EmailField(max_length=254)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("name", models.CharField(max_length=100)),
                ("father_name", models.CharField(max_length=100)),
                ("age", models.IntegerField()),
                ("dob", models.DateField()),
                ("gender", models.CharField(max_length=10)),
                (
                    "mobile",
                    models.CharField(
                        max_length=10,
                        validators=[django.core.validators.RegexValidator("^\\d{10}$")],
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("address", models.TextField()),
                ("constituency", models.CharField(max_length=100)),
                ("photo", models.ImageField(upload_to="voter_docs/photos/")),
                ("proof", models.FileField(upload_to="voter_docs/proofs/")),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
